# Note: this is only used for the Hetzner-DNS certificate generation (webhook solver in cluster-issuer.yaml)

apiVersion: v1
kind: Secret
metadata:
  name: hetzner-secret
  namespace: cert-manager
type: Opaque
data:
  api-key: ${ENCODED_SECRET}
