apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: admin@think-ahead.tech
    server: https://acme-v02.api.letsencrypt.org/directory # production environment
    # server: https://acme-staging-v02.api.letsencrypt.org/directory # staging environment
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: issuer-account-key
    # Add a single challenge solver, HTTP01
    solvers:
      - http01:
          ingress:
            class: nginx
    # solvers:
    # - dns01:
    #     webhook:
    #       # This group needs to be configured when installing the helm package, otherwise the webhook won't have permission to create an ACME challenge for this API group.
    #       groupName: think-ahead.dev
    #       solverName: hetzner
    #       config:
    #         secretName: hetzner-secret
    #         zoneName: think-ahead.dev # (Optional): When not provided the Zone will searched in Hetzner API by recursion on full domain name
    #         apiUrl: https://dummytestthinkahead.free.beeceptor.com
